services:
  jwizard-vault:
    container_name: jwizard-vault
    image: hashicorp/vault:1.14
    ports:
      - '${JWIZARD_VAULT_PORT}:8200'
    volumes:
      - ./.volumes/vault/vault-volume:/vault/data:rw
      - ./.volumes/vault:/vault/config
      - ./.env:/.env
    environment:
      - 'VAULT_ADDR=http://127.0.0.1:8200'
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl
    networks:
      - jwizard-network

  jwizard-mysql-db:
    container_name: jwizard-mysql-db
    image: mysql:8.0.32
    ports:
      - '${JWIZARD_MYSQL_PORT}:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${JWIZARD_MYSQL_PASSWORD}'
      - 'MYSQL_DATABASE=jwizard-db'
    volumes:
      - ./.volumes/mysql/mysql-volume:/var/lib/mysql
      - ./.volumes/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p$root"
    networks:
      - jwizard-network

  jwizard-minio-s3:
    container_name: jwizard-minio-s3
    image: bitnami/minio:2023.9.27
    user: root
    ports:
      - '${JWIZARD_S3_API_PORT}:9000'
      - '${JWIZARD_S3_UI_PORT}:9001'
    environment:
      - 'MINIO_ROOT_USER=${JWIZARD_S3_USERNAME}'
      - 'MINIO_ROOT_PASSWORD=${JWIZARD_S3_PASSWORD}'
      - 'MINIO_DEFAULT_BUCKETS=jwizard-static:public'
      - 'MINIO_SCHEME=http'
    volumes:
      - ./.volumes/s3/s3-volume:/bitnami/minio/data
      - ./.volumes/s3/content:/content
      - ./.volumes/s3/put-files:/put-files
    healthcheck:
      test: 'curl --fail http://localhost:9000/minio/health/live || exit 1'
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - jwizard-network

  jwizard-lava-node-1:
    container_name: jwizard-lava-node-1
    image: ghcr.io/lavalink-devs/lavalink:latest
    user: root
    restart: unless-stopped
    ports:
      - '${JWIZARD_LAVA_NODE_1_PORT}:${JWIZARD_LAVA_NODE_1_PORT}'
    expose:
      - ${JWIZARD_LAVA_NODE_1_PORT}
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=${JWIZARD_LAVA_NODE_1_PORT}
      # plugins
      - LAVALINK_PLUGINS_0_DEPENDENCY=dev.lavalink.youtube:youtube-plugin:${JWIZARD_LAVA_YT_SOURCE_VERSION}
      # server
      - LAVALINK_SERVER_PASSWORD=${JWIZARD_LAVA_NODE_1_TOKEN}
      - LAVALINK_SERVER_SOURCES_YOUTUBE=false
      # filters
      - LAVALINK_SERVER_FILTERS_VOLUME=true
      - LAVALINK_SERVER_BUFFER_DURATION_MS=400
      - LAVALINK_SERVER_FRAME_BUFFER_DURATION_MS=5000
      - LAVALINK_SERVER_OPUS_ENCODING_QUALITY=10
      - LAVALINK_SERVER_RESAMPLING_QUALITY=MEDIUM
      - LAVALINK_SERVER_TRACK_STUCK_THRESHOLD_MS=10000
      - LAVALINK_SERVER_USE_SEEK_GHOSTING=true
      # logging
      - LOGGING_REQUEST_ENABLED=true
      - LOGGING_REQUEST_INCLUDE_CLIENT_INFO=true
      - LOGGING_REQUEST_INCLUDE_HEADERS=false
      - LOGGING_REQUEST_INCLUDE_QUERY_STRING=true
      - LOGGING_REQUEST_INCLUDE_PAYLOAD=true
      - LOGGING_REQUEST_MAX_PAYLOAD_LENGTH=10000
      # yt plugin
      - PLUGINS_YOUTUBE_ENABLED=true
      - PLUGINS_YOUTUBE_OAUTH_ENABLED=true
      - PLUGINS_YOUTUBE_ALLOW_SEARCH=true
      - PLUGINS_YOUTUBE_ALLOW_DIRECT_VIDEO_IDS=true
      - PLUGINS_YOUTUBE_ALLOW_DIRECT_PLAYLIST_IDS=true
      - PLUGINS_YOUTUBE_CLIENTS_0=MUSIC
      - PLUGINS_YOUTUBE_CLIENTS_1=ANDROID_TESTSUITE
      - PLUGINS_YOUTUBE_CLIENTS_2=WEB
      - PLUGINS_YOUTUBE_CLIENTS_3=TVHTML5EMBEDDED
    volumes:
      - ./.volumes/lavalink/lavalink-1-volume/plugins:/opt/Lavalink/plugins/
    networks:
      - jwizard-network

  jwizard-lava-node-2:
    container_name: jwizard-lava-node-2
    image: ghcr.io/lavalink-devs/lavalink:latest
    user: root
    restart: unless-stopped
    ports:
      - '${JWIZARD_LAVA_NODE_2_PORT}:${JWIZARD_LAVA_NODE_2_PORT}'
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=${JWIZARD_LAVA_NODE_2_PORT}
      # plugins
      - LAVALINK_PLUGINS_0_DEPENDENCY=dev.lavalink.youtube:youtube-plugin:${JWIZARD_LAVA_YT_SOURCE_VERSION}
      # server
      - LAVALINK_SERVER_PASSWORD=${JWIZARD_LAVA_NODE_2_TOKEN}
      - LAVALINK_SERVER_SOURCES_YOUTUBE=false
      # filters
      - LAVALINK_SERVER_FILTERS_VOLUME=true
      - LAVALINK_SERVER_BUFFER_DURATION_MS=400
      - LAVALINK_SERVER_FRAME_BUFFER_DURATION_MS=5000
      - LAVALINK_SERVER_OPUS_ENCODING_QUALITY=10
      - LAVALINK_SERVER_RESAMPLING_QUALITY=MEDIUM
      - LAVALINK_SERVER_TRACK_STUCK_THRESHOLD_MS=10000
      - LAVALINK_SERVER_USE_SEEK_GHOSTING=true
      # logging
      - LOGGING_REQUEST_ENABLED=true
      - LOGGING_REQUEST_INCLUDE_CLIENT_INFO=true
      - LOGGING_REQUEST_INCLUDE_HEADERS=false
      - LOGGING_REQUEST_INCLUDE_QUERY_STRING=true
      - LOGGING_REQUEST_INCLUDE_PAYLOAD=true
      - LOGGING_REQUEST_MAX_PAYLOAD_LENGTH=10000
      # yt plugin
      - PLUGINS_YOUTUBE_ENABLED=true
      - PLUGINS_YOUTUBE_OAUTH_ENABLED=true
      - PLUGINS_YOUTUBE_ALLOW_SEARCH=true
      - PLUGINS_YOUTUBE_ALLOW_DIRECT_VIDEO_IDS=true
      - PLUGINS_YOUTUBE_ALLOW_DIRECT_PLAYLIST_IDS=true
      - PLUGINS_YOUTUBE_CLIENTS_0=MUSIC
      - PLUGINS_YOUTUBE_CLIENTS_1=ANDROID_TESTSUITE
      - PLUGINS_YOUTUBE_CLIENTS_2=WEB
      - PLUGINS_YOUTUBE_CLIENTS_3=TVHTML5EMBEDDED
    volumes:
      - ./.volumes/lavalink/lavalink-2-volume/plugins:/opt/Lavalink/plugins/
    networks:
      - jwizard-network

networks:
  jwizard-network:
    driver: bridge
