version: '3.8'

services:
  jwizard-vault:
    container_name: jwizard-vault
    image: hashicorp/vault:1.14
    ports:
      - '${JWIZARD_VAULT_PORT}:8200'
    volumes:
      - ./.volumes/vault/vault-volume:/vault/data:rw
      - ./.volumes/vault:/vault/config
      - ./.env:/.env
    environment:
      - 'VAULT_ADDR=http://127.0.0.1:8200'
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl
    networks:
      - jwizard-network

  jwizard-mysql-db:
    container_name: jwizard-mysql-db
    image: mysql:8.0.32
    ports:
      - '${JWIZARD_MYSQL_PORT}:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${JWIZARD_MYSQL_PASSWORD}'
      - 'MYSQL_DATABASE=jwizard-db'
    volumes:
      - ./.volumes/mysql/mysql-volume:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -u root -p$root"
    networks:
      - jwizard-network

networks:
  jwizard-network:
    driver: bridge