version: '3.8'

services:
  jwizard-vault:
    container_name: jwizard-vault
    image: hashicorp/vault:1.14
    ports:
      - '${JWIZARD_VAULT_PORT}:8200'
    volumes:
      - ./.volumes/vault/vault-volume:/vault/data:rw
      - ./.volumes/vault:/vault/config
      - ./.env:/.env
    environment:
      - 'VAULT_ADDR=http://127.0.0.1:8200'
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl
    networks:
      - jwizard-network

  jwizard-mysql-db:
    container_name: jwizard-mysql-db
    image: mysql:8.0.32
    ports:
      - '${JWIZARD_MYSQL_PORT}:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${JWIZARD_MYSQL_PASSWORD}'
      - 'MYSQL_DATABASE=jwizard-db'
    volumes:
      - ./.volumes/mysql/mysql-volume:/var/lib/mysql
      - ./.volumes/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysqladmin ping -u root -p$root"
    networks:
      - jwizard-network

  jwizard-minio-s3:
    container_name: jwizard-minio-s3
    image: bitnami/minio:2023.9.27
    user: root
    ports:
      - '${JWIZARD_S3_API_PORT}:9000'
      - '${JWIZARD_S3_UI_PORT}:9001'
    environment:
      - 'MINIO_ROOT_USER=${JWIZARD_S3_USERNAME}'
      - 'MINIO_ROOT_PASSWORD=${JWIZARD_S3_PASSWORD}'
      - 'MINIO_DEFAULT_BUCKETS=jwizard-static:public'
      - 'MINIO_SCHEME=http'
    volumes:
      - ./.volumes/s3/s3-volume:/bitnami/minio/data
      - ./.volumes/s3/content:/content
      - ./.volumes/s3/put-files:/put-files
    healthcheck:
      test: 'curl --fail http://localhost:9000/minio/health/live || exit 1'
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - jwizard-network

networks:
  jwizard-network:
    driver: bridge
