version: '3.8'

services:
  jwizard-vault:
    container_name: jwizard-vault
    image: hashicorp/vault:1.14
    ports:
      - '${JWIZARD_VAULT_PORT}:8200'
    volumes:
      - ./.volumes/${JWIZARD_RUNTIME}/vault/vault-volume:/vault/data:rw
      - ./.volumes/${JWIZARD_RUNTIME}/vault:/vault/config
      - ./.env:/.env
    environment:
      - 'VAULT_ADDR=http://127.0.0.1:8200'
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.hcl
    networks:
      - jwizard-network

  jwizard-mongo-db:
    container_name: jwizard-mongo-db
    image: bitnami/mongodb:6.0.13
    user: root
    ports:
      - '${JWIZARD_MONGODB_PORT}:27017'
    volumes:
      - './.volumes/${JWIZARD_RUNTIME}/db/mongo-volume:/bitnami/mongodb/data/db'
    environment:
      - 'MONGODB_ROOT_PASSWORD=${JWIZARD_MONGODB_PASSWORD}'
    networks:
      - jwizard-network

networks:
  jwizard-network:
    driver: bridge