#!/bin/sh

set -e
set -u

mounted_env_path="../../.env"
secret_name="jwizard"

get_env_variable() {
  variable_name=$1
  if [ -f "$mounted_env_path" ]; then
    while IFS= read -r line; do
      if [[ "$line" =~ ^[[:space:]]*# || "$line" =~ ^[[:space:]]*$ ]]; then
        continue
      fi
      name=$(echo "$line" | cut -d '=' -f 1)
      name=$(echo "$name" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
      if [ "$name" = "$variable_name" ]; then
        value=$(echo "$line" | cut -d '=' -f 2-)
        value=$(echo "$value" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        echo "$value"
        return
      fi
    done < "$mounted_env_path"
  fi
  echo ""
}

vault operator unseal "$(get_env_variable "JWIZARD_VAULT_UNSEAL_KEY")"

vault_token="$(get_env_variable "JWIZARD_VAULT_ROOT_TOKEN")"
export VAULT_TOKEN=$vault_token

vault secrets disable $secret_name
vault secrets enable -path=$secret_name kv

vault kv put "$secret_name/common" \
  V_JDA_APP_ID="$(get_env_variable "JWIZARD_JDA_APP_ID")" \
  V_JDA_SECRET="$(get_env_variable "JWIZARD_JDA_SECRET")" \
  V_JWT_SECRET_KEY="$(get_env_variable "JWIZARD_JWT_SECRET_KEY")" \
  V_MYSQL_USERNAME="$(get_env_variable "JWIZARD_MYSQL_USERNAME")" \
  V_MYSQL_PASSWORD="$(get_env_variable "JWIZARD_MYSQL_PASSWORD")"
