#!/bin/sh

set -e
set -u

mc_alias="minio-temp-client"
mc_host="http://localhost:9000"
mc_access_key=$MINIO_ROOT_USER
mc_secret_key=$MINIO_ROOT_PASSWORD

bucket="jwizard-static"
entry_dir="/content"

mc config host add $mc_alias \
  $mc_host \
  "$mc_access_key" "$mc_secret_key" \
  --api S3v4 \
  --lookup path

upload_files() {
  local source_dir="$1"
  local target_dir="$2"

  for item in "$source_dir"/*; do
    if [ ! -e "$item" ]; then
      continue
    fi
    if [ -d "$item" ]; then
      local dir_name=$(basename "$item")
      local new_target_dir="$target_dir/$dir_name"
      upload_files "$item" "$new_target_dir"
    elif [ -f "$item" ]; then
      local file_name=$(basename "$item")
      mc cp "$item" "$mc_alias/$bucket/$target_dir/$file_name"
    fi
  done
}

upload_files "$entry_dir" ""

mc config host rm $mc_alias
