#!/bin/sh

set -e
set -u

mounted_env_path="../../.env"
secret_name="jwizard"

get_env_variable() {
  variable_name=$1
  if [ -f "$mounted_env_path" ]; then
    while IFS="=" read -r name value; do
      if [ "$name" = "$variable_name" ]; then
        echo "$value" | tr -d '\r'
        return
      fi
    done <"$mounted_env_path"
  fi
  echo ""
}

vault operator unseal "$(get_env_variable "JWIZARD_VAULT_UNSEAL_KEY")"

vault_token="$(get_env_variable "JWIZARD_VAULT_ROOT_TOKEN")"
export VAULT_TOKEN=$vault_token

vault secrets disable $secret_name
vault secrets enable -path=$secret_name kv

vault kv put "$secret_name/common" \
  V_JDA_DEV_APP_ID="$(get_env_variable "JWIZARD_JDA_DEV_APP_ID")" \
  V_JDA_DEV_SECRET="$(get_env_variable "JWIZARD_JDA_DEV_SECRET")" \
  V_JDA_PROD_APP_ID="$(get_env_variable "JWIZARD_JDA_PROD_APP_ID")" \
  V_JDA_PROD_SECRET="$(get_env_variable "JWIZARD_JDA_PROD_SECRET")" \
  V_JWT_SECRET_KEY="$(get_env_variable "JWIZARD_JWT_SECRET_KEY")"

vault kv put "$secret_name/jwizard-api" \
  V_MONGODB_USERNAME="$(get_env_variable "JWIZARD_MONGODB_USERNAME")" \
  V_MONGODB_PASSWORD="$(get_env_variable "JWIZARD_MONGODB_PASSWORD")"
